[locations]
; Path to where your base game is installed
game_path = /home/mbiiez/openjk

; Path to your Movie Battles II Folder
mbii_path = /home/mbiiez/openjk/MBII

; Path to your Base Folder
base_path = /home/mbiiez/openjk/base

; Path to your instance config JSON files
config_path = /home/mbiiez/vmb2m/configs

[dedicated]
; Dedicated Server Engine name
engine = mbiided.i386

; MBII folder name
game = MBII
